openapi: 3.0.0

paths:
  /:
    post:
      summary: Saves information about votes
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionLogin.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" #never changes
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
        
    get:
      summary: Returns information about users
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${FunctionSignin.Arn}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST" #never changes
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"